[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "snowcli"
dynamic = ["version"]
requires-python = ">=3.7"
description = "Snowflake CLI"
dependencies = [
  "click",
  "snowflake-connector-python",
  "requirements-parser",
  "prettytable",
  "toml",
  "pyyaml"
]

[project.scripts]
snow = "snowcli.cli:main"

[tool.hatch.version]
path = "src/__about__.py"

[tool.hatch.build.targets.sdist]
exclude = [
  "/.github",
]

[tool.hatch.build.targets.wheel]
packages = ["src/snowcli", "src/templates"]
